#!/bin/bash

DEST="$HOME/local"

echo "install the git-qing software under $DEST"

if [ ! -d $DEST ]; then
  echo "$DEST does not exist, create one (Y/N)?"
  read YN
  if [ "$YN" = "y" ] || [ "$YN" = "Y" ]; then
    mkdir -p $DEST
  else
    exit 1
  fi
fi

mkdir -p $DEST/git-qing
#get the basedir of the install script
basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
chmod +w $DEST/git-qing/git-qing 2>/dev/null
chmod +w $DEST/git-qing/sh/* 2>/dev/null
cp -rp $basedir/git-qing $DEST/git-qing
cp -rp $basedir/sh $DEST/git-qing
cp -rp $basedir/LICENSE $DEST/git-qing
cp -rp $basedir/README.md $DEST/git-qing
cp -rp $basedir/VERSION $DEST/git-qing
cp -rp $basedir/plugins $DEST/git-qing
cp -rp $basedir/templates $DEST/git-qing
chmod -w $DEST/git-qing/git-qing
chmod -w $DEST/git-qing/sh/*

echo "\
Done!

Please add git-qing into the search path
Examples:
For bash or similar, add the following line into .bashrc or a similar file
   export PATH=\$PATH:$DEST/git-qing
For csh or similar, add the following line into .cshrc or a similar file
   setenv PATH \$PATH:$DEST/git-qing"
