#!/bin/bash
# upload local mega files to a mirror if needed and save a snapshot to HPSS
#
basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
workTreeTop=$( git rev-parse --show-toplevel 2>/dev/null )
source $basedir/mirror.sh #set up the correct MIRROR variable for differnt platforms

srcdir=$1
list=$workTreeTop/.git/tmp.uploadlist
cpexe=$workTreeTop/.git/tmp_copy_mega_files
hpssx=$workTreeTop/.git/tmp_save_to_hpss
echo "comparing local mega space with MIRROR-$MIRROR ..."
mkdir -p $MIRROR # if dstdir not existed, create one to avoid trivial errors
git mega compareDirs $srcdir $MIRROR | grep -v "not found" 1>$list
if [ -s $list ]; then # list not empty
  echo "$workTreeTop/.plugins-mega/copymegafiles.sh $list $workTreeTop/.mega $MIRROR" > $cpexe
  chmod a+x $cpexe
  echo -e "\nfiles to be uploaded:"
  cat $list
  echo -e "-------------------------------------------------------------------------"
  echo -e "\nsudo su - mygrp\nand then run the following command under mygrp"
  echo "   $cpexe"
  echo -e  "\nafter that, back to the user account, run 'git mega upload' again to make sure no more mega files need to be uploaded"
  exit
else
  echo "no more REGULAR mega files needs to be uploaded"
fi

# save to HPSS
HEAD=$(git rev-parse HEAD)
random_number=$((1 + RANDOM % 10000))
rnd=$(printf "%02d\n" $random_number)
dstHPSS=$HPSS_DIR/$(date +"%Y%m%d-%H%M%S")-${HEAD:0:10}-${PLATFORM}-rnd${rnd}.tar
echo -e "source /etc/profile.d/modules.sh\nmodule load hpss\ncd $MIRROR\nhtar -cvf $dstHPSS *" > $hpssx
chmod a+x $hpssx

echo -e "\nsave a snapshot of MIRROR to HPSS as follows:\n(do this only when necessary)"
echo -e "\nsudo su - mygrp\nand then run the following command under mygrp"
echo -e "    $hpssx\n"
#
# todo: write out rsync scripts/documentations to rsync MIRRORs among different platfroms
#
