#!/bin/bash
# upload local qing files to a mirror if needed
#
basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
workTreeTop=$( git rev-parse --show-toplevel 2>/dev/null )
source $basedir/mirror.sh #set up the correct MIRROR variable for differnt platforms

srcdir=$1
list=$workTreeTop/.git/tmp.uploadlist
cpexe=$workTreeTop/.git/tmp_copy_qing_files
echo "comparing local qing space with MIRROR-$MIRROR ..."
mkdir -p $MIRROR # if dstdir not existed, create one to avoid trivial errors
git qing compareDirs $srcdir $MIRROR | grep -v "not found" 1>$list
set +x
if [ -s $list ]; then # list not empty
  echo "$workTreeTop/.plugins-qing/copyqingfiles.sh $list $workTreeTop/.qing $MIRROR" > $cpexe
  chmod a+x $cpexe
  echo -e "\nfiles to be uploaded:"
  cat $list
  echo -e "-------------------------------------------------------------------------"
  echo -e "\nrun the following command to upload to MIRROR-$MIRROR"
  echo "   $cpexe"
  echo -e  "\nafter that, run 'git qing upload' again to make sure no more qing files need to be uploaded"
  exit
else
  echo "no more REGULAR qing files needs to be uploaded"
fi
