#!/bin/bash
# upload local mega files to a mirror if needed
#
basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
workTreeTop=$( git rev-parse --show-toplevel 2>/dev/null )
source $basedir/mirror.sh #set up the correct MIRROR variable for differnt platforms

srcdir=$1
list=$workTreeTop/.git/tmp.uploadlist
cpexe=$workTreeTop/.git/tmp_copy_mega_files
echo "comparing local mega space with MIRROR-$MIRROR ..."
mkdir -p $MIRROR # if dstdir not existed, create one to avoid trivial errors
git mega compareDirs $srcdir $MIRROR | grep -v "not found" 1>$list
set +x
if [ -s $list ]; then # list not empty
  echo "$workTreeTop/.plugins-mega/copymegafiles.sh $list $workTreeTop/.mega $MIRROR" > $cpexe
  chmod a+x $cpexe
  echo -e "\nfiles to be uploaded:"
  cat $list
  echo -e "-------------------------------------------------------------------------"
  echo -e "\nrun the following command to upload to MIRROR-$MIRROR"
  echo "   $cpexe"
  echo -e  "\nafter that, run 'git mega upload' again to make sure no more mega files need to be uploaded"
  exit
else
  echo "no more REGULAR mega files needs to be uploaded"
fi
